[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol'
]
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer = true
optimizer_runs = 10_000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
