name: Format Frontend Code

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install
      working-directory: ./apps/frontend

    - name: Run pnpm format
      run: pnpm format
      working-directory: ./apps/frontend

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style: format frontend code with pnpm format"
        file_pattern: "apps/frontend/**/*"
